[package]
name = "libp2p-learner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "0.52", features = ["full"]}
futures = { version = "0.3"}
tokio = { version = "1.33"} 
